### ISSUE TITLE
Upstream Thunderbird profile

### ISSUE THREAD

**Issue by u451f** [simondeziel/aa-profiles#3]
Hello!

I can't find your Thunderbird profile here: https://bazaar.launchpad.net/~apparmor-dev/apparmor-profiles/master/files/head:/ubuntu/16.04/ 
Did you already try to get it included upstream? It might be worthwile, I think.

Cheers!

**Comment by simondeziel** [comment]
I just started using 16.04 few days ago so I'd like to let the profile bake a little more before proposing it.

That said, I upload the version I'm currently using in here. If you can test it out that'd be great.

**Comment by u451f** [comment]
Hi,

I'm using Debian Jessie and I modified your profile to work there (older version of aa which does not accept variables unfortunately). It has until now only one problem, I use Icedove/Enigmail/Torbirdy:

type=AVC msg=audit(1452193483.030:3595): apparmor="DENIED" operation="exec" name="/usr/bin/gpg" pid=31088 comm="icedove" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0

**Comment by simondeziel** [comment]
In commit:b69aa4d3f143b, I dropped support for gpg since gpg2 is required by recent enigmail versions.

Now that I checked more closely, it seems the move from gpg to gpg2 is Ubuntu specific: http://changelogs.ubuntu.com/changelogs/pool/universe/e/enigmail/enigmail_1.8.2-0ubuntu0.14.04.1/changelog:

  * Depend on gnupg2 instead of gnupg. Whilst this enigmail version still
    works with gnupg 1.4.*, it pops up an alert warning that it will be the
    last version to do so

So either you start using gpg2 or I bring back support for gpg. Let me know which you chose.

Thanks for the feedback!

**Comment by u451f** [comment]
I've asked Debian GnuPG maintainers when GPG2 will be the default in Debian. I think for now it's only in experimental, so if we want a shared aa-profile repository, and we actually do, then probably we should include gpg too.

Do you know what OpenSuSe uses as per default? - I think it's important to keep cross-distro compatibility and profile sharing - at least that's what we at the Debian AppArmor packaging team and OpenSuSe maintainers want to improve on in the future.

For now,  I've added a gpg profile next to your gpg2 profile and this works well.

**Comment by simondeziel** [comment]
I brought back the gpg sub-profile as cross-distro compatibility is important. However, since I'm only using Ubuntu, I won't be able to properly test it so let me know of any issue.

**Comment by u451f** [comment]
Hi Simon,

thanks a lot! I've asked dkg about GPG2 in Debian and he told us that as gpg and gpg2 are co-installable, Thunderbird/Icedove would prefer gpg2 over gpg, if it is installed. So I think that having both subprofiles is the right way to go until gpg is really deprecated in all distributions.

Thanks a lot for working on this!

One last question though: will you submit this profile upstream (maybe you did and I missed the email on the AppArmor list)? We'd like to include it in Tails - and our policy is to try to include things upstream first and to not create any delta.

**Comment by simondeziel** [comment]
Merge proposal: https://code.launchpad.net/~sdeziel/apparmor-profiles/usr.bin.thunderbird-profile/+merge/282383
