### ISSUE TITLE
Include directive for Thunderbird addons?

### ISSUE THREAD

**Issue by u451f** [simondeziel/aa-profiles#4]
Hi Simon,

not sure if this here is the right place to inform you about a suggestion by intrigeri (see https://mailman.boum.org/pipermail/tails-icedove/2016-February/000145.html)

> I think a profile for Thunderbird/Icedove should have provisions to be extended by
> other packages such as xul-ext-*. I would recommend using an #include
> directive to source a .d directory, where extension packages can drop
> the snippet they need.

From my understanding this is if such extensions would ship their own profile. 
I've never seen this though.

If you prefer that I send this to the apparmor mailing list instead, please let me know :)

Cheers and thanks again for your work.

**Comment by simondeziel** [comment]
Hi u451f,

On 2016-02-05 12:59 PM, u451f wrote:
> not sure if this here is the right place to inform you about a
> suggestion by intrigeri (see
> https://mailmanboumorg/pipermail/tails-icedove/2016-February/000145html)
> 
>     I think a profile for Thunderbird/Icedove should have provisions to
>     be extended by
>     other packages such as xul-ext-* I would recommend using an #include
>     directive to source a d directory, where extension packages can drop
>     the snippet they need
> 
> If you prefer that I send this to the apparmor mailing list instead,
> please let me know :)

The mailing list seems the best place IMHO. Thanks and sorry for the
delay in response.

Regards,
Simon
